version: "3"

services:
   db_node_domain:
     image: mysql:8.0
     command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
     volumes:
       - /root/auto-server/data/config/back_files/wordpress/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress_wp
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db_node_domain
     image: wordpress:latest
     restart: always
     environment:
       VIRTUAL_HOST: example.test.com
       LETSENCRYPT_HOST: example.test.com
       DEFAULT_EMAIL: xxx@gmail.com
       WORDPRESS_DB_HOST: db_node_domain:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

networks:
  default:
    external:
      name: nginx-proxy