version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing    
    environment:
      - PUID=0                      
      - PGID=0                      
      - TZ=Europe/London
    volumes:
      - ./path/to/appdata/config:/config   
      - ./path/to/data1:/data1
      - ./path/to/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
