version: '3'
services:
    web:
        environment:
          - VIRTUAL_HOST=example.test.com
          - LETSENCRYPT_HOST=example.test.com
          - DEFAULT_EMAIL=xxx@gmail.com
        image: nginx:latest
        volumes:
            - /root/auto-server/data/config/back_files/filesServer/app:/home/wwwroot/
            - /root/auto-server/data/config/back_files/filesServer/config/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.0-fpm
        volumes:
            - /root/auto-server/data/config/back_files/filesServer/app:/home/wwwroot/

networks:
  default:
    external:
      name: nginx-proxy